# Generated by Django 5.2.15 on 2026-06-14 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeTai',
            fields=[
                ('MaDeTai', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã đề tài')),
                ('TenDeTai', models.CharField(max_length=255, verbose_name='Tên đề tài')),
                ('TomTat', models.TextField(verbose_name='Tóm tắt')),
                ('TrangThai', models.CharField(choices=[('CHODUYET', 'Chờ Duyệt'), ('DANGTHUCHIEN', 'Đang Thực Hiện'), ('CHONGHIEMTHU', 'Chờ Nghiệm Thu')], default='CHODUYET', max_length=20, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Đề Tài',
                'verbose_name_plural': 'Danh Sách Đề Tài',
                'db_table': 'DeTai',
            },
        ),
        migrations.CreateModel(
            name='HoiDong',
            fields=[
                ('MaHoiDong', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã hội đồng')),
                ('TenHoiDong', models.CharField(max_length=200, verbose_name='Tên hội đồng')),
                ('QuyetDinh', models.CharField(max_length=100, verbose_name='Số quyết định')),
            ],
            options={
                'verbose_name': 'Hội Đồng',
                'verbose_name_plural': 'Danh Sách Hội Đồng',
                'db_table': 'HoiDong',
            },
        ),
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('TenDangNhap', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Tên đăng nhập')),
                ('MatKhauHash', models.CharField(max_length=255, verbose_name='Mật khẩu (hash)')),
                ('QuyenHan', models.CharField(choices=[('SINHVIEN', 'Sinh Viên'), ('GIANGVIEN', 'Giảng Viên'), ('QUANLY', 'Cán Bộ Quản Lý')], max_length=20, verbose_name='Quyền hạn')),
                ('TrangThai', models.IntegerField(default=1, verbose_name='Trạng thái')),
            ],
            options={
                'verbose_name': 'Tài Khoản',
                'verbose_name_plural': 'Danh Sách Tài Khoản',
                'db_table': 'TaiKhoan',
            },
        ),
        migrations.CreateModel(
            name='BaoCao',
            fields=[
                ('MaBaoCao', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã báo cáo')),
                ('DuongDanFile', models.CharField(max_length=500, verbose_name='Đường dẫn file báo cáo')),
                ('TyLeDaoVan', models.FloatField(blank=True, null=True, verbose_name='Tỷ lệ đạo văn (%)')),
                ('NgayNop', models.DateTimeField(verbose_name='Ngày nộp')),
                ('MaDeTai', models.ForeignKey(db_column='MaDeTai', on_delete=django.db.models.deletion.CASCADE, related_name='bao_caos', to='api.detai', verbose_name='Đề tài')),
            ],
            options={
                'verbose_name': 'Báo Cáo',
                'verbose_name_plural': 'Danh Sách Báo Cáo',
                'db_table': 'BaoCao',
                'ordering': ['-NgayNop'],
            },
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('MaSV', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã sinh viên')),
                ('TenSV', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('Lop', models.CharField(max_length=20, verbose_name='Lớp')),
                ('Khoa', models.CharField(max_length=100, verbose_name='Khoa')),
                ('MaDeTai', models.ForeignKey(blank=True, db_column='MaDeTai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sinh_viens', to='api.detai', verbose_name='Đề tài')),
                ('TenDangNhap', models.OneToOneField(db_column='TenDangNhap', on_delete=django.db.models.deletion.CASCADE, related_name='sinh_vien', to='api.taikhoan', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Sinh Viên',
                'verbose_name_plural': 'Danh Sách Sinh Viên',
                'db_table': 'SinhVien',
            },
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('MaGV', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã giảng viên')),
                ('TenGV', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('HocHamHocVi', models.CharField(max_length=50, verbose_name='Học hàm/Học vị')),
                ('TenDangNhap', models.OneToOneField(db_column='TenDangNhap', on_delete=django.db.models.deletion.CASCADE, related_name='giang_vien', to='api.taikhoan', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Giảng Viên',
                'verbose_name_plural': 'Danh Sách Giảng Viên',
                'db_table': 'GiangVien',
            },
        ),
        migrations.CreateModel(
            name='CanBoQuanLy',
            fields=[
                ('MaCB', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Mã cán bộ')),
                ('TenCB', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('PhongBan', models.CharField(max_length=100, verbose_name='Phòng/Ban')),
                ('TenDangNhap', models.OneToOneField(db_column='TenDangNhap', on_delete=django.db.models.deletion.CASCADE, related_name='can_bo', to='api.taikhoan', verbose_name='Tài khoản')),
            ],
            options={
                'verbose_name': 'Cán Bộ Quản Lý',
                'verbose_name_plural': 'Danh Sách Cán Bộ Quản Lý',
                'db_table': 'CanBoQuanLy',
            },
        ),
        migrations.CreateModel(
            name='TienDo',
            fields=[
                ('MaTienDo', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã tiến độ')),
                ('TyLeHoanThanh', models.IntegerField(verbose_name='Tỷ lệ hoàn thành (%)')),
                ('NoiDung', models.TextField(verbose_name='Nội dung cập nhật')),
                ('FileMinhChung', models.CharField(blank=True, max_length=500, verbose_name='File minh chứng (đường dẫn)')),
                ('NgayCapNhat', models.DateTimeField(auto_now_add=True, verbose_name='Ngày cập nhật')),
                ('MaDeTai', models.ForeignKey(db_column='MaDeTai', on_delete=django.db.models.deletion.CASCADE, related_name='tien_dos', to='api.detai', verbose_name='Đề tài')),
            ],
            options={
                'verbose_name': 'Tiến Độ',
                'verbose_name_plural': 'Nhật Ký Tiến Độ',
                'db_table': 'TienDo',
                'ordering': ['-NgayCapNhat'],
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDanhGia', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã đánh giá')),
                ('DiemSo', models.FloatField(verbose_name='Điểm số')),
                ('NhanXet', models.TextField(verbose_name='Nhận xét')),
                ('XepLoai', models.CharField(choices=[('XUATSAC', 'Xuất Sắc'), ('GIOI', 'Giỏi'), ('KHA', 'Khá'), ('TRUNGBINH', 'Trung Bình'), ('KHONGDAT', 'Không Đạt')], max_length=20, verbose_name='Xếp loại')),
                ('MaDeTai', models.ForeignKey(db_column='MaDeTai', on_delete=django.db.models.deletion.CASCADE, related_name='danh_gias', to='api.detai', verbose_name='Đề tài')),
                ('MaHoiDong', models.ForeignKey(db_column='MaHoiDong', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_gias', to='api.hoidong', verbose_name='Hội đồng')),
            ],
            options={
                'verbose_name': 'Đánh Giá',
                'verbose_name_plural': 'Danh Sách Đánh Giá',
                'db_table': 'DanhGia',
                'unique_together': {('MaHoiDong', 'MaDeTai')},
            },
        ),
        migrations.CreateModel(
            name='HuongDan',
            fields=[
                ('MaHuongDan', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã hướng dẫn')),
                ('VaiTro', models.CharField(max_length=50, verbose_name='Vai trò')),
                ('MaDeTai', models.ForeignKey(db_column='MaDeTai', on_delete=django.db.models.deletion.CASCADE, related_name='huong_dans', to='api.detai', verbose_name='Đề tài')),
                ('MaGV', models.ForeignKey(db_column='MaGV', on_delete=django.db.models.deletion.CASCADE, related_name='huong_dans', to='api.giangvien', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Phân Công Hướng Dẫn',
                'verbose_name_plural': 'Danh Sách Hướng Dẫn',
                'db_table': 'HuongDan',
                'unique_together': {('MaDeTai', 'MaGV')},
            },
        ),
    ]
