# Generated by Django 5.2.15 on 2026-06-16 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detai',
            name='DiemTongHop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detai',
            name='LyDoTuChoi',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detai',
            name='MaHoiDong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='de_tais', to='api.hoidong', verbose_name='Hội đồng đánh giá'),
        ),
        migrations.AddField(
            model_name='huongdan',
            name='DaXacNhan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='huongdan',
            name='NgayXacNhan',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiendo',
            name='NgayNhanXet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tiendo',
            name='NhanXetGVHD',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='detai',
            name='TrangThai',
            field=models.CharField(choices=[('CHODUYET', 'Chờ Duyệt'), ('DANGTHUCHIEN', 'Đang Thực Hiện'), ('CHONGHIEMTHU', 'Chờ Nghiệm Thu'), ('DANGHIEMTHU', 'Đã Nghiệm Thu'), ('TUCHOI', 'Từ Chối')], default='CHODUYET', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
