# Generated by Django 5.2.15 on 2026-06-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detai_diemtonghop_detai_lydotuchoi_detai_mahoidong_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaiBaoNCKH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TenDeTai', models.CharField(max_length=300, verbose_name='Tên đề tài / bài báo')),
                ('TacGia', models.CharField(max_length=200, verbose_name='Tác giả / Chủ trì')),
                ('NamHoanThanh', models.PositiveIntegerField(verbose_name='Năm hoàn thành')),
                ('GiaiThuong', models.CharField(choices=[('NHAT', 'Giải Nhất'), ('NHI', 'Giải Nhì'), ('BA', 'Giải Ba'), ('KHUYENKHICH', 'Giải Khuyến Khích'), ('XUATSAC', 'Xuất Sắc')], max_length=20, verbose_name='Giải thưởng')),
                ('AnhBia', models.URLField(blank=True, default='', max_length=500, verbose_name='Ảnh bìa (URL)')),
                ('TomTat', models.TextField(blank=True, default='', verbose_name='Tóm tắt (hiển thị trên card)')),
                ('NoiDungChiTiet', models.TextField(blank=True, default='', verbose_name='Nội dung chi tiết (HTML)')),
                ('IsActive', models.BooleanField(default=True, verbose_name='Hiển thị trên trang chủ')),
                ('NgayTao', models.DateTimeField(auto_now_add=True)),
                ('NgayCapNhat', models.DateTimeField(auto_now=True)),
                ('DeTai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_baos', to='api.detai', verbose_name='Đề tài nội bộ (nếu có)')),
            ],
            options={
                'verbose_name': 'Bài Báo NCKH',
                'verbose_name_plural': 'Danh Sách Bài Báo NCKH',
                'db_table': 'BaiBaoNCKH',
                'ordering': ['-NamHoanThanh', 'TenDeTai'],
            },
        ),
    ]
