# Generated by Django 5.2.15 on 2026-06-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_them_baibao_nckh'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThanhVienHoiDong',
            fields=[
                ('MaThanhVien', models.AutoField(primary_key=True, serialize=False)),
                ('VaiTro', models.CharField(choices=[('CHUTICH', 'Chủ tịch Hội đồng'), ('THUKY', 'Thư ký'), ('UYVIEN', 'Ủy viên')], max_length=20)),
                ('MaGV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoi_dong_thamgia', to='api.giangvien')),
                ('MaHoiDong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_viens', to='api.hoidong')),
            ],
            options={
                'verbose_name': 'Thành Viên Hội Đồng',
                'verbose_name_plural': 'Danh Sách Thành Viên Hội Đồng',
                'db_table': 'ThanhVienHoiDong',
                'unique_together': {('MaHoiDong', 'MaGV')},
            },
        ),
    ]
