# Generated by Django 5.2.15 on 2026-06-19 11:54

import api.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_them_thanhvien_hoidong_va_filefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baocao',
            name='DuongDanFile',
        ),
        migrations.AddField(
            model_name='baocao',
            name='FileBaoCao',
            field=models.FileField(blank=True, null=True, upload_to='bao_cao_files/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), api.models.validate_file_size], verbose_name='File báo cáo'),
        ),
        migrations.AddField(
            model_name='danhgia',
            name='ThanhVienCham',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phieu_diem', to='api.thanhvienhoidong', verbose_name='Thành viên chấm điểm'),
        ),
        migrations.AddField(
            model_name='detai',
            name='NgayTao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày đăng ký'),
        ),
    ]
