# Generated by Django 5.2.15 on 2026-06-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_baocao_duongdanfile_baocao_filebaocao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiendo',
            name='FileMinhChung',
            field=models.FileField(blank=True, null=True, upload_to='tien_do_files/%Y/%m/', verbose_name='File minh chứng'),
        ),
    ]
