# Generated by Django 5.2.15 on 2026-06-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tiendo_fileminhchung'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiendo',
            name='DiemGVHD',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm GVHD chấm'),
        ),
    ]
