# Generated by Django 5.2.15 on 2026-06-20 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_tiendo_diemgvhd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiendo',
            name='NoiDung',
        ),
    ]
