# Generated by Django 5.2.15 on 2026-06-21 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_canboquanly_email_canboquanly_sodienthoai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanhvienhoidong',
            name='MaThanhVien',
        ),
        migrations.RemoveField(
            model_name='thanhvienhoidong',
            name='VaiTro',
        ),
        migrations.AddField(
            model_name='thanhvienhoidong',
            name='VaiTroHD',
            field=models.CharField(choices=[('Chủ tịch hội đồng', 'Chủ tịch hội đồng'), ('Thư ký hội đồng', 'Thư ký hội đồng'), ('Ủy viên phản biện 1', 'Ủy viên phản biện 1'), ('Ủy viên phản biện 2', 'Ủy viên phản biện 2'), ('Ủy viên hội đồng', 'Ủy viên hội đồng')], default='Ủy viên hội đồng', max_length=50, verbose_name='Vai trò trong HĐ'),
        ),
        migrations.AddField(
            model_name='thanhvienhoidong',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thanhvienhoidong',
            name='MaGV',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.giangvien'),
        ),
        migrations.AlterField(
            model_name='thanhvienhoidong',
            name='MaHoiDong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_vien', to='api.hoidong'),
        ),
    ]
