# Generated by Django 5.2.15 on 2026-06-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_thanhvienhoidong_mathanhvien_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaiLieu',
            fields=[
                ('MaTaiLieu', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã tài liệu')),
                ('TenTaiLieu', models.CharField(max_length=255, verbose_name='Tên tài liệu/văn bản')),
                ('Loai', models.CharField(choices=[('Biểu mẫu', 'Biểu mẫu'), ('Quy định', 'Quy định'), ('Hướng dẫn', 'Hướng dẫn')], max_length=20, verbose_name='Loại tài liệu')),
                ('DuongLink', models.URLField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn liên kết')),
                ('FileDinhKem', models.FileField(blank=True, null=True, upload_to='library_docs/%Y/', verbose_name='File tải lên (.pdf/.docx)')),
                ('NgayTao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Tài liệu thư viện',
                'verbose_name_plural': 'Tài liệu thư viện',
                'db_table': 'TaiLieu',
                'ordering': ['-NgayTao'],
            },
        ),
    ]
