# Generated by Django 5.2.15 on 2026-06-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tailieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailieu',
            name='DinhDang',
            field=models.CharField(choices=[('Word', 'Word'), ('PDF', 'PDF')], default='Word', max_length=10, verbose_name='Định dạng tệp'),
        ),
        migrations.AddField(
            model_name='tailieu',
            name='MoTa',
            field=models.TextField(blank=True, default='', verbose_name='Mô tả tóm tắt nội dung'),
        ),
        migrations.AlterField(
            model_name='tailieu',
            name='DuongLink',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn tải file về (URL tệp mẫu)'),
        ),
    ]
