# Generated by Django 5.2.15 on 2026-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_tailieu_dinhdang_tailieu_mota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huongdan',
            name='DaXacNhan',
        ),
        migrations.AddField(
            model_name='huongdan',
            name='TrangThaiXacNhan',
            field=models.CharField(choices=[('CHO_XAC_NHAN', 'Chờ xác nhận'), ('DA_XAC_NHAN', 'Đã đồng ý hướng dẫn'), ('TU_CHOI', 'Đã từ chối hướng dẫn')], default='CHO_XAC_NHAN', max_length=20),
        ),
        migrations.AlterField(
            model_name='detai',
            name='TrangThai',
            field=models.CharField(choices=[('CHODUYET', 'Chờ cán bộ duyệt'), ('CHO_XAC_NHAN_GV', 'Chờ giảng viên xác nhận'), ('GV_TU_CHOI', 'Giảng viên từ chối hướng dẫn'), ('DANGTHUCHIEN', 'Đang thực hiện'), ('CHONGHIEMTHU', 'Chờ nghiệm thu'), ('DANGHIEMTHU', 'Đã nghiệm thu'), ('TUCHOI', 'Bị từ chối')], default='CHODUYET', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
