# Generated by Django 5.2.15 on 2026-06-22 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_huongdan_daxacnhan_huongdan_trangthaixacnhan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baocao',
            name='DiemTrungBinh',
            field=models.FloatField(blank=True, null=True, verbose_name='Điểm trung bình Hội đồng'),
        ),
        migrations.AddField(
            model_name='baocao',
            name='MaHoiDong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_bao_cao', to='api.hoidong', verbose_name='Hội đồng đánh giá'),
        ),
    ]
