# Generated by Django 5.2.15 on 2026-06-22 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_baocao_diemtrungbinh_baocao_mahoidong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhgia',
            name='MaHoiDong',
            field=models.ForeignKey(blank=True, db_column='MaHoiDong', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_gias', to='api.hoidong', verbose_name='Hội đồng'),
        ),
    ]
