# Generated by Django 5.2.15 on 2026-06-22 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_danhgia_mahoidong'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('MaThongBao', models.AutoField(primary_key=True, serialize=False, verbose_name='Mã thông báo')),
                ('NoiDung', models.TextField(verbose_name='Nội dung thông báo')),
                ('IsRead', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('Loai', models.CharField(choices=[('TIENDO', 'Tiến độ & Chấm điểm'), ('DETAI', 'Phê duyệt Đề tài'), ('HOIDONG', 'Hội đồng nghiệm thu'), ('HETHONG', 'Thông báo Hệ thống')], default='HETHONG', max_length=20, verbose_name='Loại thông báo')),
                ('NgayTao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('TenDangNhap', models.ForeignKey(db_column='TenDangNhap', on_delete=django.db.models.deletion.CASCADE, related_name='thong_baos', to='api.taikhoan', verbose_name='Tài khoản nhận')),
            ],
            options={
                'verbose_name': 'Thông Báo',
                'verbose_name_plural': 'Danh Sách Thông Báo',
                'db_table': 'ThongBao',
                'ordering': ['-NgayTao'],
            },
        ),
    ]
