# Generated by Django 5.2.15 on 2026-06-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_thongbao'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='danhgia',
            unique_together={('ThanhVienCham', 'MaDeTai')},
        ),
    ]
