import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';



export const metadata: Metadata = {
  title: "Hệ thống quản lý NCKH Học viện kỹ thuật mật mã",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <AntdRegistry>
          {children}
        </AntdRegistry>
      </body>
    </html>
  );
}
